### ISSUE TITLE
What has it changed?

### ISSUE THREAD

**Issue by XCXDSHS** [Ripazhakgggdkp/zeropussy-releases#1]
I found a bunch of music after unzipping it, is this just the music that changed the game

**Comment by jamilchioino-keynua** [comment]
The project is collaborative and has been on hold for some time. However, here's a list of stuff that made it in.

https://ripazhakgggdkp.github.io/zeropussy-public-issues/

**Comment by Ripazhakgggdkp** [comment]
The project has been on hold for a while, however, you can check out what was planned and what made it in here:

https://ripazhakgggdkp.github.io/zeropussy-public-issues/

**Comment by XCXDSHS** [comment]
Thank you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月15日(星期三) 晚上10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ripazhakgggdkp/zeropussy-releases] What has it changed? (Issue #1)





 
The project has been on hold for a while, however, you can check out what was planned and what made it in here:
 
https://ripazhakgggdkp.github.io/zeropussy-public-issues/

**Comment by XCXDSHS** [comment]
I fixed the problem that part of the text in the music options was not displayed (I also encountered this problem when I helped the old version of the Chinese language patch be transplanted to the latest version), and made a new differential patch without any other changes. I don’t know if this is correct. Could you please help, I found you in discord and sent you the patch there
Also, this is a good mode
